export default {
    status: {
        isFetchingCurriculumsHeadersList: false,
    //     isCreating: false,
    //     isUpdating: false,
    //     isDeleting: false
    },

    selection: {
        _id: null,
        // The Rest of the parameters are also included
        title: ""
    },

    // usersHeadersList: [
    //     {
    //         _id: "",
    //         username: "",
    //         email: "",
    //         role: "",
    //         tags: [],
    //         firstName: "",
    //         middleName: "",
    //         lastName: "",

    //         // Summary of the tasks generated by the backend
    //         tasks:
    //             [
    //                 {
    //                     title: "",
    //                     totalExperiments: 0,
    //                     completedExperiments: 0,
    //                     unfinishedExperiment: false
    //                 }
    //             ]
    //     }
    // ]
} 
