version: "3.5"
services:
  learn:
    container_name: clasp-webapp
    build: music_paradigm_web
    ports:
      - 81:8080
    environment:
      - NODE_ENV=production
      - VIRTUAL_HOST=learn.coffeylab.ca
      - LETSENCRYPT_HOST=learn.coffeylab.ca
      - LESTENCRYPT_EMAIL=emily@coffeylab.ca
      - VIRTUAL_PORT=8080
    depends_on:
      - claspweb

  claspweb:
    container_name: clasp-api
    build: music_paradigm_api
    ports:
      - 4000:4000
    environment:
      - NODE_ENV=production
      - DEFAULT_ADMIN_USERNAME=LabMaster
      - DEFAULT_ADMIN_PASSWORD=CoffeyLabInConcordia
    depends_on:
      - mongo
    volumes:
      - ./experiment_ressources:/usr/src/experiment_ressources

  mongo:
    container_name: claspmongo
    image: mongo
    volumes:
      - ./db:/data/db:rw
    healthcheck:
      test: echo 'db.runCommand("ping").ok' | mongo mongo:27017/test --quiet
      interval: 10s
      timeout: 10s
      retries: 5
      start_period: 40s

  mongo-express:
    image: mongo-express
    environment:
      - ME_CONFIG_MONGODB_SERVER=claspmongo
    ports:
      - 8080:8081
    depends_on:
      - mongo
