import { validator } from "@/_helpers";

export default {
    status: {
        isFetchingUsersHeadersList: false,
        isCreating: false,
        isUpdating: false,
        isDeleting: false
    },

    edition: validator.getMinimalValidExperimentStructure(),
    selection: {
        _id: null,
        content: validator.getMinimalValidExperimentStructure()
    },
    usersHeadersList: [
        {
            _id: "",
            username: "",
            email: "",
            role: "",
            groups: "",
            firstName: "",
            middleName: "",
            lastName: "",
            
            // Summary of the tasks generated by the backend
            tasks:
                [
                    {
                        title: "",
                        totalExperiments: 0,
                        completedExperiments: 0,
                        unfinishedExperiment: false
                    }
                ]
        }
    ]
} 
