version: '2'
services:
  nginx:
    image: nginx
    labels:
        com.github.jrcs.letsencrypt_nginx_proxy_companion.nginx_proxy: "true"
    container_name: nginx
    restart: always
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ${NGINX_FILES_PATH}/conf.d:/etc/nginx/conf.d
      - ${NGINX_FILES_PATH}/htpasswd:/etc/nginx/htpasswd:ro
      - ${NGINX_FILES_PATH}/vhost.d:/etc/nginx/vhost.d
      - ${NGINX_FILES_PATH}/html:/usr/share/nginx/html
      - ${NGINX_FILES_PATH}/certs:/etc/nginx/certs:ro
      - ./dhparam.pem:/etc/nginx/dhparam/dhparam.pem:ro
  
  nginx-gen:
    image: jwilder/docker-gen
    command: -notify-sighup nginx -watch -wait 5s:30s /etc/docker-gen/templates/nginx.tmpl /etc/nginx/conf.d/default.conf
    container_name: nginx-gen
    restart: always
    volumes:
      - ${NGINX_FILES_PATH}/conf.d:/etc/nginx/conf.d
      - ${NGINX_FILES_PATH}/htpasswd:/etc/nginx/htpasswd:ro
      - ${NGINX_FILES_PATH}/vhost.d:/etc/nginx/vhost.d
      - ${NGINX_FILES_PATH}/html:/usr/share/nginx/html
      - ${NGINX_FILES_PATH}/certs:/etc/nginx/certs:ro
      - /var/run/docker.sock:/tmp/docker.sock:ro
      - ./nginx.tmpl:/etc/docker-gen/templates/nginx.tmpl:ro

  nginx-letsencrypt:
    image: jrcs/letsencrypt-nginx-proxy-companion
    container_name: nginx-letsencrypt
    restart: always
    volumes:
      - ${NGINX_FILES_PATH}/conf.d:/etc/nginx/conf.d
      - ${NGINX_FILES_PATH}/htpasswd:/etc/nginx/htpasswd:ro
      - ${NGINX_FILES_PATH}/vhost.d:/etc/nginx/vhost.d
      - ${NGINX_FILES_PATH}/html:/usr/share/nginx/html
      - ${NGINX_FILES_PATH}/certs:/etc/nginx/certs:rw
      - /var/run/docker.sock:/var/run/docker.sock:ro
    environment:
      - NGINX_DOCKER_GEN_CONTAINER="nginx-gen"
      - NGINX_PROXY_CONTAINER="nginx"

  learn:
    container_name: clasp-webapp
    build: music_paradigm/music_paradigm_web
    restart: always
    environment:
      - VIRTUAL_HOST=${HOST_FRONTEND_SERVER}
      - LETSENCRYPT_HOST=${HOST_FRONTEND_SERVER}
      - LESTENCRYPT_EMAIL=${MANAGEMENT_EMAIL}
      - NODE_ENV=production
      - VIRTUAL_PORT=8080
    depends_on:
      - claspweb

  claspweb:
    container_name: clasp-api
    build: music_paradigm/music_paradigm_api
    restart: always
    environment:
      - VIRTUAL_HOST=${HOST_BACKEND_SERVER}
      - VIRTUAL_PORT=4000
      - LETSENCRYPT_HOST=${HOST_BACKEND_SERVER}
      - LETSENCRYPT_EMAIL=${MANAGEMENT_EMAIL}
      - NODE_ENV=production
    depends_on:
      - claspmongo
    volumes:
      - ./music_paradigm/experiment_resources:/usr/src/experiment_resources

  claspmongo:
    container_name: claspmongo
    image: mongo
    restart: always
    volumes:
      - ./db:/data/db:rw

  mongo-express:
     image: mongo-express
     restart: always
     environment:
      - ME_CONFIG_MONGODB_SERVER=claspmongo
      - VIRTUAL_HOST=${HOST_DATABASE_MANAGER}
      - VIRTUAL_PORT=8081
      - LETSENCRYPT_HOST=${HOST_DATABASE_MANAGER}
      - LETSENCRYPT_EMAIL=${MANAGEMENT_EMAIL}



