const jsonWebToken = require('jsonwebtoken');
const config = require('config.json');

module.exports = {
    generateToken
};

/**
 * Function to gernerate a JWT token
 * @param {Object} user         The user for which a token must be created 
 * @param {string} user._id     The ID of the user, as generated by MongoDB
 * @param {string} user.role    The role associated to the user
 * @return {string}             The JWT token generated for the user
 */
function generateToken(user) {
    // Creation of the jwt token
    const token = jsonWebToken.sign(
        {
            sub: user._id,
            role: user.role
        },
        config.secret);
    return token;
}