const BLOCK_TYPE_CUE = 'cue';
const BLOCK_TYPE_END = 'end';
const BLOCK_TYPE_FEEDBACK = 'feedback';
const BLOCK_TYPE_GLT = 'glt';
const BLOCK_TYPE_INSTRUCTION = 'instruction';
const BLOCK_TYPE_PLAYING = 'playing';
const BLOCK_TYPE_PVT = 'pvt';
const BLOCK_TYPE_QUESTION = 'question';
const BLOCK_TYPE_REST = 'rest';
const BLOCK_TYPE_SURVEY = 'survey';
const BLOCK_TYPE_VIDEO = 'video';
const BLOCK_TYPE_QRITTING = 'writting';


const ALL_BLOCK_TYPES = [
    BLOCK_TYPE_CUE,
    BLOCK_TYPE_END,
    BLOCK_TYPE_FEEDBACK,
    BLOCK_TYPE_GLT,
    BLOCK_TYPE_INSTRUCTION,
    BLOCK_TYPE_PLAYING,
    BLOCK_TYPE_PVT,
    BLOCK_TYPE_QUESTION,
    BLOCK_TYPE_REST,
    BLOCK_TYPE_SURVEY,
    BLOCK_TYPE_VIDEO,
    BLOCK_TYPE_QRITTING,
];

export default {
    ALL_BLOCK_TYPES,
    BLOCK_TYPE_CUE,
    BLOCK_TYPE_END,
    BLOCK_TYPE_FEEDBACK,
    BLOCK_TYPE_GLT,
    BLOCK_TYPE_INSTRUCTION,
    BLOCK_TYPE_PLAYING,
    BLOCK_TYPE_PVT,
    BLOCK_TYPE_QUESTION,
    BLOCK_TYPE_REST,
    BLOCK_TYPE_SURVEY,
    BLOCK_TYPE_VIDEO,
    BLOCK_TYPE_QRITTING,
};
